### ISSUE TITLE
Android: Missing SDK API 19

### ISSUE THREAD

**Issue by katho** [ARDroneSDK3/ARSDKBuildUtils#21]
Hello everyone, I have a question:
Using Ubuntu 14.04 when running ./CheckEnv.py I get this:

-- Checking if your environment will build the ARSDK for different platforms --

[[ Should work, Won't work, Not tested, may work ]]

Generic             : OK !
iOS                 : Bad platform `linux`, you need to be on ['darwin'] to build the target `iOS`
Unix                : Missing binary `nasm`
/bin/sh: 1: android: not found
Android             : Missing Android SDK for API 19 (Android 4.4.2), please install it.

I've configured the android sdk/ndk paths properly and the SDK API 19 exists, maybe I'm missing something but I'm confused.
Thanks for the attention in advance.

**Comment by N-Bz** [comment]
Hi,

That's probably because you don't have the `android` binary into your `PATH`.
The `CheckEnv.py` script needs it to check whether you have the good SDK installed. If we can't check, we assume that it is not here.

Basically, add `$ANDROID_SDK_PATH/tools/` to your `PATH` and you're good to go !

Regards,
Nicolas.

**Comment by katho** [comment]
You're right Nicolas, now it's done, thank you!
