### ISSUE TITLE
Android: Missing  library '-llog-

### ISSUE THREAD

**Issue by mzambrini** [ARDroneSDK3/ARSDKBuildUtils#8]
Command './CheckEnv.py' fail with message "Android: Missing  library '-llog-" .

I'm on Ubuntu 14.04.1 LTS 64 bit.
Any hint?

Thanks

**Comment by N-Bz** [comment]
This means that your Android toolchain can not find the android logging library (so we can write to logcat).

If this is the only message you have in the Android section for the `./CheckEnv.py` script, it may be because your Android standalone toolchains are not properly configured.

Did you follow all the instructions from the [install readme file](https://github.com/ARDroneSDK3/Docs/blob/master/Installation/INSTALL) ?

Can you also check that the ndk toolchains in your path are not hidden by another toolchain of the same name: check that running `which arm-linux-androideabi-gcc` returns the path to the standalone toolchain that you made for the SDK, and not the binary inside the `android-ndk-rxx` folder.

Regards,
Nicolas.

**Comment by weaversa** [comment]
I'm also having this problem. I've narrowed it down to the `make-standalone-toolchain.sh` script overwriting the libraries in the `sysroot` directory during subsequent calls. That is, I am having trouble creating and keeping the libraries for `arm`, `mips`, and `x86` separate.

I don't think the problem I'm having is related to your project, but any help you can give would be greatly appreciated. I'm sure there is something simple I'm missing.

Specifically, if I create the `arm` libraries like so:
```
[ARSDKBuildUtils]$ $ANDROID_NDK_PATH/build/tools/make-standalone-toolchain.sh --platform=android-14 --arch=arm --install-dir=/usr/local
Auto-config: --toolchain=arm-linux-androideabi-4.8
Copying prebuilt binaries...
Copying sysroot headers and libraries...
Copying c++ runtime headers and libraries...
Copying files to: /usr/local
Cleaning up...
Done.
```
Then the `CheckEnv.py` works great:
```
[ARSDKBuildUtils]$ ./CheckEnv.py 
-- Checking if your environment will build the ARSDK for different platforms --

[[ Should work, Won't work, Not tested, may work ]]

Generic             : OK !
iOS                 : OK !
Unix                : OK !
Android             : OK !
```
However, after creating the `mips` libraries, the `CheckEnv.py` script fails:
```
[ARSDKBuildUtils]$ $ANDROID_NDK_PATH/build/tools/make-standalone-toolchain.sh --platform=android-14 --arch=mips --install-dir=/usr/local
Auto-config: --toolchain=mipsel-linux-android-4.8
Copying prebuilt binaries...
Copying sysroot headers and libraries...
Copying c++ runtime headers and libraries...
Copying files to: /usr/local
Cleaning up...
Done.
[ARSDKBuildUtils]$ ./CheckEnv.py 
-- Checking if your environment will build the ARSDK for different platforms --

[[ Should work, Won't work, Not tested, may work ]]

Generic             : OK !
iOS                 : OK !
Unix                : OK !
Android             : Missing library `-llog`
```
Here I took the test from the `CheckEnv.py` script and try to compile it directly. It works fine w/ the `mips` `gcc` (because I had just created those libraries.
```
[ARSDKBuildUtils]$ cat test.c
int main(int argc, char *argv[]) { return 0; }

[ARSDKBuildUtils]$ mipsel-linux-android-gcc -o test.o test.c -llog
```
However, rebuilding the `mips` libraries overwrote the `ar` libraries, and now I cannot compile using `arm`.
```
[ARSDKBuildUtils]$ arm-linux-androideabi-gcc -o test.o test.c -llog
/usr/local/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: fatal error: /usr/local/bin/../sysroot/usr/lib/crtbegin_dynamic.o: unsupported ELF machine number 8
collect2: error: ld returned 1 exit status
```

**Comment by N-Bz** [comment]
Hmm... 

For your issue @weaversa, it's pretty simple (and I'll edit the install readme accordingly).

In our setups, we generate the three android toolchain in separate directories (let's call them `~/Android/toolchain-<arch>`), and add each `~/Android/toolchain-<arch>/bin` to our path in our `~/.bashrc` file.

So, to summarize, when installing a new computer at work, the android ndk part is done like this:

```
$ANDROID_NDK_PATH/build/tools/make-standalone-toolchain.sh --platform=android-14 --arch=arm --install-dir=~/Android/toolchain-arm
$ANDROID_NDK_PATH/build/tools/make-standalone-toolchain.sh --platform=android-14 --arch=x86 --install-dir=~/Android/toolchain-x86
$ANDROID_NDK_PATH/build/tools/make-standalone-toolchain.sh --platform=android-14 --arch=mips --install-dir=~/Android/toolchain-mips
```

Then in `.bashrc` we add at the end:
```
export PATH=$PATH:~/Android/toolchain-arm/bin:~/Android/toolchain-x86/bin:~/Android/toolchain-mips/bin
```


Hope this helped you ;)

Regards,
Nicolas.

**Comment by mzambrini** [comment]
Thanks Nicolas,
I was wrong.
I have not followed your instructions correctly.

Max

**Comment by weaversa** [comment]
@N-Bz That solved this particular problem. I'll create a new ticket for my current problem. Thanks!
